import "../styles/main.scss"
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "護國神殿",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-Hant">
      <body suppressHydrationWarning={true}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
