import { Noto_Serif_TC } from 'next/font/google';
import "../styles/main.scss";
import Navbar from "@/components/Navbar";

const notoSerifTC = Noto_Serif_TC({
  subsets: ['latin'],
  display: 'swap',
  weight: '400'
});

export const metadata = {
  title: "護國神殿",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-Hant" className={notoSerifTC.className}>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
